/// <reference types="@figma/plugin-typings" />

// Plugin generated by KOGA AI
figma.showUI(__html__, { visible: false });

figma.ui.onmessage = async (msg) => {
  if (msg.type === 'run-code') {
    try {
      // Generated code starts here
      // This plugin creates two circles, one green and one orange.
// The green circle is larger than the orange circle.

// Function to create a circle
function createCircle(radius: number, color: RGB): EllipseNode {
  const circle = figma.createEllipse();
  circle.resize(radius * 2, radius * 2);
  circle.fills = [{ type: 'SOLID', color: color }];
  return circle;
}

// Create the green circle
const greenCircle = createCircle(100, { r: 0, g: 1, b: 0 }); // Green color
greenCircle.name = "Green Circle";

// Create the orange circle
const orangeCircle = createCircle(50, { r: 1, g: 0.5, b: 0 }); // Orange color
orangeCircle.name = "Orange Circle";

// Position the circles
greenCircle.x = 0;
greenCircle.y = 0;
orangeCircle.x = 150;
orangeCircle.y = 50;

// Add the circles to the current page
figma.currentPage.appendChild(greenCircle);
figma.currentPage.appendChild(orangeCircle);

// Select the new nodes
figma.currentPage.selection = [greenCircle, orangeCircle];

// Zoom to fit the selection
figma.viewport.scrollAndZoomIntoView(figma.currentPage.selection);
      
      // Select all created nodes
      const nodes = figma.currentPage.selection;
      if (nodes.length > 0) {
        figma.viewport.scrollAndZoomIntoView(nodes);
      }
      
      figma.closePlugin("Code executed successfully!");
    } catch (error) {
      console.error('Plugin error:', error);
      figma.closePlugin("Error: " + error.message);
    }
  }
};